CREATE DATABASE FastMenu;
USE FastMenu;

CREATE TABLE Cardapio (
ID INT NOT NULL AUTO_INCREMENT,
qnt_visitas INT NOT NULL DEFAULT '0',
PRIMARY KEY(ID)
);

CREATE TABLE Restaurante (
CNPJ VARCHAR(18) NOT NULL,
Nome VARCHAR(30) NOT NULL,
Telefone VARCHAR(14) NOT NULL,
Descricao VARCHAR(100) NOT NULL,
PRIMARY KEY(CNPJ)
);

CREATE TABLE Prato (
ID INT NOT NULL AUTO_INCREMENT,
Restaurante_CNPJ VARCHAR(18) NOT NULL,
Cardapio_ID INT NOT NULL,
Nome VARCHAR(25) NOT NULL,
Preco Double NOT NULL Default 0,
Descricao VARCHAR(100) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(Restaurante_CNPJ) REFERENCES Restaurante(CNPJ),
FOREIGN KEY(Cardapio_ID) REFERENCES Cardapio(ID)
);

CREATE TABLE Administrador (
CPF VARCHAR(14) NOT NULL,
Nome VARCHAR(45) NOT NULL,
Restaurante_CNPJ VARCHAR(18) NOT NULL,
Senha VARCHAR(10) NOT NULL,
Cardapio_ID INT NOT NULL,
PRIMARY KEY(CPF),
FOREIGN KEY(Restaurante_CNPJ) REFERENCES Restaurante(CNPJ),
FOREIGN KEY(Cardapio_ID) REFERENCES Cardapio(ID)
);